# Generated by Django 4.1 on 2023-06-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment',
            name='is_questions_exacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_questions_exacted',
            field=models.BooleanField(default=False),
        ),
    ]
