# Generated by Django 4.1 on 2023-06-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearning', '0002_assigment_is_questions_exacted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_questions_exacted',
            field=models.BooleanField(default=False),
        ),
    ]
