# Generated by Django 3.2 on 2023-06-20 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_subject_subject_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OnlineLearning', '0003_notes_is_questions_exacted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('school', models.CharField(max_length=255)),
                ('photo', models.FileField(null=True, upload_to='Photos')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('anaunciment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineLearning.announciment')),
                ('classSubject', models.ManyToManyField(to='schools.SubjectClass')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.department')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineLearning.studentgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
