# version: '3.8'

services:
  traefik:
    image: traefik:2.8
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
      - "./acme.json:/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik.service=traefik"
      - "traefik.http.routers.traefik.service=api@internal"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.port=80"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.rule=Host(`http://saccos.backend.safaripro.net`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  database:
    image: mysql:latest
    container_name: database
    restart: unless-stopped
    networks:
      - proxy
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.port=80"
      - "traefik.http.routers.pma.tls=true"
      - "traefik.http.routers.pma.rule=Host(`http://backendpma.safaripro.net`)"
      - "traefik.http.routers.pma.entrypoints=websecure"
      - "traefik.http.routers.pma.tls.certresolver=letsencrypt"
      - "traefik.http.routers.pma.service=pma"
      - "traefik.http.services.pma.loadbalancer.server.port=80"

  nginx:
    image: nginx
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
    ports:
      - 8001:80
    depends_on:
      - backend

networks:
  proxy:
    external: true

volumes:
  media_volume:
  static_volume:
  database:
  app:
