# Generated by Django 3.2.17 on 2023-02-11 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.subject')),
            ],
        ),
        migrations.RemoveField(
            model_name='topics',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='assigment',
            name='subtopic',
        ),
        migrations.DeleteModel(
            name='SubTopic',
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
        migrations.AddField(
            model_name='assigment',
            name='topic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Student.topic'),
            preserve_default=False,
        ),
    ]
