# Generated by Django 4.1 on 2023-06-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OnlineLearning', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('weight', models.BigIntegerField()),
                ('number_of_questions', models.BigIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Examination Format',
                'db_table': 'Examination Format',
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight_annual', models.BigIntegerField(null=True)),
                ('weight_final', models.BigIntegerField(null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('studentClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.studentclass')),
            ],
            options={
                'verbose_name': 'Examn Type',
                'db_table': 'Examn Type',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lower_marks', models.BigIntegerField()),
                ('upper_marks', models.BigIntegerField()),
                ('weight', models.BigIntegerField(null=True)),
                ('description', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schoollevel')),
            ],
            options={
                'verbose_name': 'Grade',
                'db_table': 'Grade',
            },
        ),
        migrations.CreateModel(
            name='QuestionsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_questions', models.BigIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Questions Type',
                'db_table': 'Questions Type',
            },
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('marks', models.BigIntegerField(null=True)),
                ('is_submitted', models.BigIntegerField(default=0)),
                ('date_of_exam', models.DateField()),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.examtype')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineLearning.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.subject')),
            ],
            options={
                'verbose_name': 'Student Exam',
                'db_table': 'Student Exam',
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.BigIntegerField(null=True)),
                ('grade', models.CharField(max_length=100)),
                ('average', models.BigIntegerField(null=True)),
                ('division', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.studentexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineLearning.student')),
            ],
            options={
                'verbose_name': 'Student Result',
                'db_table': 'Student Result',
            },
        ),
        migrations.CreateModel(
            name='GPAClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lower_gpa', models.BigIntegerField()),
                ('upper_gpa', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schoollevel')),
            ],
            options={
                'verbose_name': 'GPA Class',
                'db_table': 'GPA Class',
            },
        ),
        migrations.CreateModel(
            name='Generated_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answers', models.TextField()),
                ('is_generated', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('exam_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.examformat')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.examtype')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.subject')),
            ],
            options={
                'verbose_name': 'Examination Generated',
                'db_table': 'Examination Generated',
            },
        ),
        migrations.CreateModel(
            name='ExaminationDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(null=True)),
                ('answers', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('questionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.questionstype')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineLearning.topic')),
            ],
            options={
                'verbose_name': 'Examination Dump  Questions',
                'db_table': 'Examination Dump  Questions',
            },
        ),
        migrations.AddField(
            model_name='examformat',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.examtype'),
        ),
        migrations.AddField(
            model_name='examformat',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.subject'),
        ),
        migrations.AddField(
            model_name='examformat',
            name='type_questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.questionstype'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lower_point', models.BigIntegerField()),
                ('upper_point', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schoollevel')),
            ],
            options={
                'verbose_name': 'Division',
                'db_table': 'Division',
            },
        ),
    ]
