# Generated by Django 4.1 on 2023-06-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationdump',
            name='is_generated_Model',
            field=models.BooleanField(default=True),
        ),
    ]
