# Generated by Django 4.2.3 on 2023-07-11 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generated_exam',
            name='exam_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.examformat'),
        ),
    ]
