# Generated by Django 4.1 on 2023-06-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0002_examinationdump_is_generated_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
