# Generated by Django 4.1 on 2023-06-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0003_studentexam_is_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexam',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
