# Generated by Django 4.1 on 2023-06-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0006_alter_studentexam_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexam',
            name='is_submitted',
            field=models.BigIntegerField(default=0),
        ),
    ]
