# Generated by Django 3.2 on 2023-06-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0007_alter_studentexam_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='examination_identity',
            field=models.BigIntegerField(default=0),
        ),
    ]
