# Generated by Django 3.2 on 2023-06-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0008_studentexam_examination_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='generated_exam',
            name='examination_identity',
            field=models.BigIntegerField(default=0),
        ),
    ]
