# Generated by Django 3.2 on 2023-07-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0009_generated_exam_examination_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='is_result_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
