# Generated by Django 3.2 on 2023-07-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearning', '0004_teacher'),
        ('OnlineExamination', '0010_auto_20230701_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='generated_exam',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OnlineLearning.topic'),
            preserve_default=False,
        ),
    ]
