# Generated by Django 4.2.3 on 2023-07-11 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='anaunciment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineLearning.announciment'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineLearning.studentgroup'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='Photos'),
        ),
    ]
